apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
data:
  DATABASE_USER: YWRtaW4=  # YWRtaW4= est "admin" encodé en base64
  DATABASE_PASSWORD: cGFzc3dvcmQ=  # cGFzc3dvcmQ= est "password" encodé en base64